# Site settings
title: Programming Everything
motto: A wild tangent appeared!
email: lxmachina@gmail.com
description: A collection of resources for all things programming related.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hallfox.github.io" # the base hostname & protocol for your site
twitter_username: hallfox_
github_username:  hallfox

# Build settings
markdown: kramdown
